name: Generate Document

on: 
  push:
    branches:
      - "main"

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      # 変更検知するのに前回の履歴も取得
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # 変更ファイルを取得
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      # goのセットアップ
      - name: Set up golang
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.4'
      # 実行権限付与
      - name: Add Permision
        run: chmod a+x ../script/generate-documnet.sh
      # 変更ファイルがあればドキュメント更新を実行する
      - name: Run
        run: ../script/generate-document.sh

